title: Contrast Security ADR Runbooks
description: Security runbooks for Contrast Security's Attack Detection Rules
baseurl: "/adr-runbooks"
url: "https://contrast-security-oss.github.io"
repository: Contrast-Security-OSS/adr-runbooks

theme: minima
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

collections:
  runbooks:
    output: true
    permalink: /runbooks/:title/

defaults:
  - scope:
      path: ""
      type: runbooks
    values:
      layout: runbook

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
