title: Application Detection and Response Runbooks
description: Security incident response runbooks for Contrast Security's Application Detection and Response
baseurl: "/adr-runbooks"
url: "https://contrast-security-oss.github.io"

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Collections
collections:
  runbooks:
    output: true
    permalink: /:collection/:name/

# Default front matter for runbook files
defaults:
  - scope:
      path: ""
      type: "runbooks"
    values:
      layout: "runbook"
  - scope:
      path: ""
    values:
      layout: "default"

# Navigation
nav_links:
  - title: Home
    url: /
  - title: Runbooks
    url: /runbooks/
  - title: About
    url: /about/

# Theme customization
colors:
  deep_green: "#004D45"
  medium_green: "#0E9E53"
  midnight_blue: "#0A004F"
  red: "#FF6862"
  purple: "#804CF5"
  blue: "#3877FF"
  bright_green: "#40D273"
  light_blue: "#00CFFE"
  platinum_grey: "#9DA5B3"
